### ISSUE TITLE
Réglages et génération URL intégration des masques standard Dolibarr

### ISSUE THREAD

**Issue by lmag** [Eoxia/EasyURL#31]
Séparation des réglages pour la génération et pour les réglages

![image](https://github.com/Eoxia/EasyURL/assets/3288514/40716935-d333-476a-ad1c-a26d8adbbd9f)

**Comment by nicolas-eoxia** [comment]
L'intégration ne gêne plus pour les config
Finalement on fera des substitutions 



![Image](https://github.com/Eoxia/EasyURL/assets/52404047/1fd09159-794f-4076-9d62-d24154aca13e)
