### ISSUE TITLE
Rajouter un message quand on a pas set l'api pour le short et rajouter un check des credentials dans le setup

### ISSUE THREAD

**Issue by evarisk-kilyan** [Eoxia/EasyURL#74]

**Comment by SAMBILI** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
